# Generated by Django 4.0.5 on 2022-07-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("stats", models.JSONField(default=dict)),
                ("passive", models.TextField(default="passive")),
                ("active", models.TextField(default="active")),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Fighter"),
                            (1, "Marksman"),
                            (2, "Assassin"),
                            (3, "Mage"),
                            (4, "Tank"),
                            (5, "Support"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
    ]
