# Generated by Django 4.0.4 on 2022-05-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField()),
                ('passive', models.TextField(blank=True, null=True)),
                ('active', models.TextField(blank=True, null=True)),
                ('item_type', models.IntegerField(choices=[(0, 'Fighter'), (1, 'Marksman'), (2, 'Assassin'), (3, 'Mage'), (4, 'Tank'), (5, 'Support')], null=True)),
            ],
        ),
    ]
