# Generated by Django 4.0.4 on 2022-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Fighter'), (1, 'Marksman'), (2, 'Assassin'), (3, 'Mage'), (4, 'Tank'), (5, 'Support')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
