# Generated by Django 4.0.4 on 2022-06-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='type',
        ),
    ]
