# Generated by Django 4.0.5 on 2022-07-05 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Ward Skin"),
                            (1, "Skin"),
                            (2, "Champion"),
                            (3, "Material"),
                            (4, "Tactical"),
                            (5, "Eternal"),
                            (6, "Emote"),
                            (7, "Icon"),
                        ]
                    ),
                ),
                (
                    "currency",
                    models.IntegerField(
                        choices=[
                            (0, "Blue Essence"),
                            (1, "Orange Essence"),
                            (2, "Event Coins"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Loot",
            },
        ),
        migrations.CreateModel(
            name="LootOwnerShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid", models.IntegerField()),
                (
                    "loot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loot.loot"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LootImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(default="image 2.jpg", upload_to="")),
                (
                    "loot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="loot.loot",
                    ),
                ),
            ],
        ),
    ]
