# Generated by Django 4.0.4 on 2022-05-23 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lootownership',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loot', to=settings.AUTH_USER_MODEL),
        ),
    ]
