# Generated by Django 4.0.4 on 2022-05-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0002_lootownership_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
