# Generated by Django 4.0.4 on 2022-05-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0003_alter_loot_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loot',
            old_name='loot_currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='loot',
            old_name='loot_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='lootownership',
            name='purchasing_currency',
        ),
    ]
