# Generated by Django 4.0.4 on 2022-05-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0004_rename_loot_currency_loot_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LootImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('loot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_images', to='loot.loot')),
            ],
        ),
    ]
