# Generated by Django 4.0.4 on 2022-05-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0005_lootimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loot',
            name='image',
        ),
    ]
