# Generated by Django 4.0.4 on 2022-06-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0006_remove_loot_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loot',
            options={'verbose_name_plural': 'Loot'},
        ),
    ]
