# Generated by Django 4.0.4 on 2022-06-06 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loot', '0007_alter_loot_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lootimage',
            name='loot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='loot.loot'),
        ),
        migrations.AlterField(
            model_name='lootownership',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loots', to=settings.AUTH_USER_MODEL),
        ),
    ]
