# Generated by Django 4.0.5 on 2022-07-05 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("champions", "0002_championmastery_profile_championownership_player_and_more"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerseasongrade",
            name="champion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_grades",
                to="champions.champion",
            ),
        ),
        migrations.AlterField(
            model_name="playerseasongrade",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
