# Generated by Django 4.0.5 on 2022-07-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_playerseasongrade_champion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player",
                to="accounts.profile",
            ),
        ),
    ]
