# Generated by Django 4.0.4 on 2022-05-23 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_championownership_champion_championownership_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
