# Generated by Django 4.0.4 on 2022-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_player_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='server',
            field=models.IntegerField(choices=[(0, 'Euw'), (1, 'Na'), (2, 'China'), (3, 'Korea'), (4, 'Russia')], null=True),
        ),
    ]
