# Generated by Django 4.0.4 on 2022-05-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0006_remove_champion_damage_type_champion_damage_type_and_more'),
        ('loot', '0002_lootownership_player'),
        ('accounts', '0004_alter_player_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championownership',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='champions.champion'),
        ),
        migrations.AlterField(
            model_name='championownership',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='owned_champions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='champions.champion'),
        ),
        migrations.AlterField(
            model_name='player',
            name='owned_loot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loot.loot'),
        ),
        migrations.AlterField(
            model_name='player',
            name='owned_skins',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='champions.championskin'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='player',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Euw'), (1, 'Na'), (2, 'China'), (3, 'Korea'), (4, 'Russia')], null=True),
        ),
        migrations.AlterField(
            model_name='playerseasongrade',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_grades', to='champions.champion'),
        ),
        migrations.AlterField(
            model_name='playerseasongrade',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skinownership',
            name='payment_currency',
            field=models.IntegerField(blank=True, choices=[(0, 'Rp'), (1, 'Be')], null=True),
        ),
        migrations.AlterField(
            model_name='skinownership',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skins', to=settings.AUTH_USER_MODEL),
        ),
    ]
