# Generated by Django 4.0.4 on 2022-05-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_championownership_champion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank_type',
            field=models.IntegerField(choices=[(0, 'Solo Duo'), (1, 'Flex'), (2, 'Tft')], default=0),
        ),
    ]
