# Generated by Django 4.0.5 on 2022-07-08 12:33

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_playerimage_player_alter_profileimage_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="username",
            field=models.CharField(
                default="admin",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
    ]
