# Generated by Django 4.0.4 on 2022-05-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_rank_rank_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='rank_level',
            new_name='rank',
        ),
    ]
