# Generated by Django 4.0.5 on 2022-07-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_player_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="email address"
            ),
        ),
    ]
