# Generated by Django 4.0.5 on 2022-07-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_player_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileimage",
            old_name="background_pick",
            new_name="background_picture",
        ),
    ]
