# Generated by Django 4.0.4 on 2022-05-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_playerseasongrade_obtained_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='accounts.profile'),
        ),
    ]
