# Generated by Django 4.0.4 on 2022-05-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_player_player_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_pic',
            new_name='icon',
        ),
    ]
