# Generated by Django 4.0.4 on 2022-05-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_player_pic_player_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='rank_border',
            new_name='border',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='rank_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='rank_type',
            new_name='type',
        ),
    ]
