# Generated by Django 4.0.4 on 2022-05-27 15:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_rank_border_rank_border_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='honor_level',
            field=models.IntegerField(default=2, validators=[accounts.models.validate_less_than_5]),
        ),
    ]
