# Generated by Django 4.0.4 on 2022-05-28 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_honor_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='border',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='icon',
        ),
        migrations.CreateModel(
            name='RankImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('border', models.ImageField(blank=True, null=True, upload_to='')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_images', to='accounts.rank')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
