# Generated by Django 4.0.4 on 2022-05-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_rank_border_remove_rank_icon_rankimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='playerimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='background_pick',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trophy',
        ),
        migrations.AddField(
            model_name='playerimage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_pick', models.ImageField(blank=True, null=True, upload_to='')),
                ('trophy', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='accounts.profile')),
            ],
        ),
    ]
