# Generated by Django 4.0.4 on 2022-05-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_player_icon_remove_playerimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='highest_champion_mastery',
        ),
    ]
