# Generated by Django 4.0.4 on 2022-06-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_highest_champion_mastery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinownership',
            name='player',
        ),
        migrations.RemoveField(
            model_name='skinownership',
            name='skin',
        ),
        migrations.DeleteModel(
            name='ChampionOwnerShip',
        ),
        migrations.DeleteModel(
            name='SkinOwnerShip',
        ),
    ]
