# Generated by Django 4.0.4 on 2022-06-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_skinownership_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='owned_champions',
        ),
        migrations.RemoveField(
            model_name='player',
            name='owned_loot',
        ),
        migrations.RemoveField(
            model_name='player',
            name='owned_skins',
        ),
    ]
