# Generated by Django 4.0.4 on 2022-06-06 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
