# Generated by Django 4.0.4 on 2022-06-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_player_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='highest_rank',
        ),
    ]
