# Generated by Django 4.0.4 on 2022-06-08 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_profileimage_profile_alter_rankimage_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerimage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
    ]
