# Generated by Django 4.0.4 on 2022-05-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionAbilitiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1)),
                ('icon', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('video_showcase', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('look', models.ImageField(upload_to='')),
                ('has_border', models.BooleanField(default=False)),
                ('border', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EternalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group_icon', models.ImageField(upload_to='')),
                ('is_unlocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Eternals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.eternalgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('price_rp', models.IntegerField(choices=[(275, ' 275'), (975, ' 975'), (1350, ' 1350'), (1820, ' 1820'), (3250, ' 3250')])),
                ('price_be', models.IntegerField(choices=[(450, ' 450'), (1350, ' 1350'), (3150, ' 3150'), (4800, ' 4800'), (6300, ' 6300'), (7800, ' 7800')])),
                ('type', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[(0, 'Damage'), (1, 'Toughness'), (2, 'Crowd Control'), (3, 'Mobility'), (4, 'Utility')], max_length=100)),
                ('damage_Type', models.CharField(max_length=30)),
                ('style', models.ImageField(upload_to='')),
                ('difficulty', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('is_freetoplay', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('abilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.championabilitiy')),
                ('eternals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.eternals')),
                ('mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.championmastery')),
                ('skins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.championskin')),
            ],
        ),
    ]
