# Generated by Django 4.0.5 on 2022-07-05 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("champions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="championmastery",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masteries",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="championownership",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="champions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="skinownership",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="champion",
            name="abilities",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="champions.championability",
            ),
        ),
        migrations.AlterField(
            model_name="champion",
            name="skins",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="champions.championskin",
            ),
        ),
        migrations.AlterField(
            model_name="championmastery",
            name="champion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masteries",
                to="champions.champion",
            ),
        ),
        migrations.AlterField(
            model_name="championownership",
            name="champion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="champions.champion",
            ),
        ),
        migrations.AlterField(
            model_name="skinownership",
            name="skin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="champions.championskin",
            ),
        ),
    ]
