# Generated by Django 4.0.4 on 2022-05-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='damage_Type',
            field=models.IntegerField(choices=[(0, 'Attack Damage'), (1, 'Ability Power')]),
        ),
    ]
