# Generated by Django 4.0.4 on 2022-05-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0002_alter_champion_damage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eternals',
            name='group_name',
        ),
    ]
