# Generated by Django 4.0.5 on 2022-07-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("champions", "0002_championmastery_profile_championownership_player_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="championability",
            name="video_showcase",
        ),
    ]
