# Generated by Django 4.0.5 on 2022-07-09 21:23

import champions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("champions", "0003_remove_championability_video_showcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="champion",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="championability",
            name="name",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="championmastery",
            name="level",
            field=models.IntegerField(
                default=3, validators=[champions.models.validate_less_than_7]
            ),
        ),
        migrations.AlterField(
            model_name="championskin",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="eternal",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="eternalgroup",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
