# Generated by Django 4.0.4 on 2022-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0003_remove_eternals_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='category',
            field=models.IntegerField(choices=[(0, 'Damage'), (1, 'Toughness'), (2, 'Crowd Control'), (3, 'Mobility'), (4, 'Utility')], max_length=100),
        ),
    ]
