# Generated by Django 4.0.4 on 2022-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0006_remove_champion_damage_type_champion_damage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(0, ' Easy'), (1, ' Normal'), (2, ' Hard'), (3, ' Verydifficult')], null=True),
        ),
    ]
