# Generated by Django 4.0.4 on 2022-05-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0008_alter_champion_image_alter_champion_style_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChampionAbilitiy',
            new_name='ChampionAbility',
        ),
    ]
