# Generated by Django 4.0.4 on 2022-05-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0009_rename_championabilitiy_championability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championskin',
            name='has_border',
        ),
        migrations.AddField(
            model_name='championability',
            name='is_ultimate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='championability',
            name='key',
            field=models.IntegerField(),
        ),
    ]
