# Generated by Django 4.0.4 on 2022-05-27 15:25

import champions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0010_remove_championskin_has_border_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championmastery',
            name='level',
            field=models.IntegerField(validators=[champions.models.validate_less_than_7]),
        ),
    ]
