# Generated by Django 4.0.4 on 2022-05-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0011_alter_championmastery_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championmastery',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='championskin',
            name='border',
        ),
        migrations.RemoveField(
            model_name='championskin',
            name='look',
        ),
        migrations.AddField(
            model_name='championskin',
            name='skin_rarity',
            field=models.IntegerField(blank=True, choices=[(0, 'Rare'), (1, 'Epic'), (2, 'Legendary'), (3, 'Ultimate')], null=True),
        ),
        migrations.CreateModel(
            name='ChampionSkinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look', models.ImageField(blank=True, null=True, upload_to='')),
                ('border', models.ImageField(blank=True, null=True, upload_to='')),
                ('champion_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_skin_images', to='champions.championskin')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionMasteryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('champion_mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_mastery_images', to='champions.championmastery')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ImageField(blank=True, null=True, upload_to='')),
                ('style', models.ImageField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_images', to='champions.champion')),
            ],
        ),
    ]
