# Generated by Django 4.0.4 on 2022-05-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0012_remove_championmastery_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championability',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='eternalgroup',
            name='group_icon',
        ),
        migrations.RemoveField(
            model_name='eternals',
            name='icon',
        ),
        migrations.CreateModel(
            name='EternalsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('eternals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eternals_images', to='champions.eternals')),
            ],
        ),
        migrations.CreateModel(
            name='EternalGroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('eternal_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eternal_group_images', to='champions.eternalgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionAbilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('champion_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_ability_images', to='champions.championability')),
            ],
        ),
    ]
