# Generated by Django 4.0.4 on 2022-05-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0013_remove_championability_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EternalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='champion',
            old_name='eternals',
            new_name='eternal',
        ),
        migrations.RemoveField(
            model_name='eternalgroupimage',
            name='eternal_group',
        ),
        migrations.AddField(
            model_name='eternalgroupimage',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='champions.eternalgroup'),
        ),
        migrations.RenameModel(
            old_name='Eternals',
            new_name='Eternal',
        ),
        migrations.DeleteModel(
            name='EternalsImage',
        ),
        migrations.AddField(
            model_name='eternalimage',
            name='eternal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='champions.eternal'),
        ),
    ]
