# Generated by Django 4.0.4 on 2022-05-29 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_highest_champion_mastery'),
        ('champions', '0014_eternalimage_rename_eternals_champion_eternal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='eternal',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='mastery',
        ),
        migrations.RemoveField(
            model_name='championmasteryimage',
            name='champion_mastery',
        ),
        migrations.AddField(
            model_name='championmastery',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mastries', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championmasteryimage',
            name='mastery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='champions.championmastery'),
            preserve_default=False,
        ),
    ]
