# Generated by Django 4.0.4 on 2022-05-30 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_highest_champion_mastery'),
        ('champions', '0015_remove_champion_eternal_remove_champion_mastery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championmastery',
            name='champion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mastries', to='champions.champion'),
        ),
        migrations.AddField(
            model_name='eternal',
            name='champion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='champions.champion'),
        ),
        migrations.AlterField(
            model_name='championmastery',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mastries', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='eternal',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='champions.eternalgroup'),
        ),
    ]
