# Generated by Django 4.0.4 on 2022-06-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0020_alter_championmastery_champion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
