# Generated by Django 4.0.4 on 2022-06-05 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('champions', '0021_champion_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championability',
            options={'verbose_name_plural': 'Abillities'},
        ),
        migrations.AlterModelOptions(
            name='championmastery',
            options={'verbose_name_plural': 'Mastries'},
        ),
        migrations.AlterModelOptions(
            name='championskin',
            options={'verbose_name_plural': 'Skins'},
        ),
        migrations.AlterField(
            model_name='championabilityimage',
            name='champion_ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='champions.championability'),
        ),
        migrations.AlterField(
            model_name='championimage',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='champions.champion'),
        ),
        migrations.AlterField(
            model_name='championskinimage',
            name='champion_skin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='champions.championskin'),
        ),
        migrations.CreateModel(
            name='SkinOwnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.IntegerField()),
                ('payment_currency', models.IntegerField(blank=True, choices=[(0, 'Rp'), (1, 'Be')], null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skins', to=settings.AUTH_USER_MODEL)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.championskin')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionOwnerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.IntegerField()),
                ('payment_currency', models.IntegerField(choices=[(0, 'Rp'), (1, 'Be')])),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='champions.champion')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
