# Generated by Django 4.0.4 on 2022-06-06 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_skinownership_player_and_more'),
        ('champions', '0022_alter_championability_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championmastery',
            options={'verbose_name_plural': 'Masteries'},
        ),
        migrations.AlterField(
            model_name='championmastery',
            name='champion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='champions.champion'),
        ),
        migrations.AlterField(
            model_name='championmastery',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='accounts.profile'),
        ),
    ]
