# Generated by Django 4.0.4 on 2022-06-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0025_alter_champion_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championability',
            name='video_showcase',
        ),
    ]
