# Generated by Django 4.0.4 on 2022-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0026_remove_championability_video_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='championability',
            name='video_showcase',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
