# Generated by Django 4.0.4 on 2022-06-09 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0027_championability_video_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='abilities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='champions.championability'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='skins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='champions.championskin'),
        ),
    ]
