# Generated by Django 4.0.4 on 2022-06-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0028_alter_champion_abilities_alter_champion_skins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championskin',
            name='skin_rarity',
            field=models.IntegerField(choices=[(0, 'Rare'), (1, 'Epic'), (2, 'Legendary'), (3, 'Ultimate')], default=0),
        ),
    ]
